# Generated by Django 4.0.1 on 2022-01-20 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_remove_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
