# Generated by Django 4.0.1 on 2022-01-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(max_length=500),
        ),
    ]
